common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  # socket: /tmp/mysql.sock

development:
  database: onyx_curation_dev
  <<: *common

test:
  database: onyx_curation_test
  <<: *common

production:
  database: onyx_curation_prod
  <<: *common

cucumber:
  database: onyx_curation_cucumber
  <<: *common
