common: &common
  adapter: mysql2
  encoding: utf8
  reconnect: false
  pool: 5
  username: root
  password:
  # socket: /tmp/mysql.sock

development:
  database: social_war_dev
  <<: *common

test:
  database: social_war_test
  <<: *common

production:
  database: social_war_prod
  <<: *common

cucumber:
  database: social_war_cucumber
  <<: *common

